///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryEntity {
  /*
{
  "id": "NDBlMDBiY2ItMGNlOC00MmQyLWI4ZjMtYjIwMTM0MmU1Zjk5",
  "name": "Bệnh thường gặp ở trẻ em",
  "description": "Tổng hợp các bài thuốc liên quan tới các bệnh thường gặp ở trẻ em",
  "icon": "",
  "iconType": "lucide",
  "iconSize": null,
  "className": null,
  "isActive": true,
  "code": "BENH_TRE_EM",
  "allowEdit": true,
  "categoryTypeId": "NGRkNzAxY2EtNjhmNi00Nzk4LWFmMjItNTE5YjEyYzg5MGIx",
  "sortOrder": 0,
  "isDefault": false,
  "createBy": "1",
  "createdAt": "2025-07-31T08:19:56.000Z",
  "updatedAt": "2025-07-31T08:20:04.000Z"
} 
*/

  String? id;
  String? name;
  String? description;
  String? nameEN;
  String? descriptionEN;
  String? icon;
  String? iconType;
  String? iconSize;
  String? className;
  bool? isActive;
  String? code;
  bool? allowEdit;
  String? categoryTypeId;
  int? sortOrder;
  bool? isDefault;
  String? createBy;
  String? createdAt;
  String? updatedAt;
  // Parent-child support: id của danh mục cha (null nếu là root)
  String? parentId;
  // Tuỳ response của BE: có thể là object cha lồng vào hoặc null
  CategoryEntity? parent;
  // Khi BE trả tree (get-tree-by-category-type), children chứa danh mục con
  List<CategoryEntity>? children;
  // Đường dẫn ảnh đại diện. BE trả relative path -> client prepend storageHost
  String? image;
  // Mã màu HEX (#RRGGBB hoặc #RRGGBBAA) dùng làm tone chính cho card UI
  String? color;

  CategoryEntity({
    this.id,
    this.name,
    this.description,
    this.nameEN,
    this.descriptionEN,
    this.icon,
    this.iconType,
    this.iconSize,
    this.className,
    this.isActive,
    this.code,
    this.allowEdit,
    this.categoryTypeId,
    this.sortOrder,
    this.isDefault,
    this.createBy,
    this.createdAt,
    this.updatedAt,
    this.parentId,
    this.parent,
    this.children,
    this.image,
    this.color,
  });
  CategoryEntity.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    nameEN = json['nameEN']?.toString();
    descriptionEN = json['descriptionEN']?.toString();
    icon = json['icon']?.toString();
    iconType = json['iconType']?.toString();
    iconSize = json['iconSize']?.toString();
    className = json['className']?.toString();
    isActive = json['isActive'];
    code = json['code']?.toString();
    allowEdit = json['allowEdit'];
    categoryTypeId = json['categoryTypeId']?.toString();
    sortOrder = json['sortOrder']?.toInt();
    isDefault = json['isDefault'];
    createBy = json['createBy']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    parentId = json['parentId']?.toString();
    if (json['parent'] is Map<String, dynamic>) {
      parent = CategoryEntity.fromJson(
        json['parent'] as Map<String, dynamic>,
      );
    }
    if (json['children'] is List) {
      children = (json['children'] as List)
          .whereType<Map<String, dynamic>>()
          .map(CategoryEntity.fromJson)
          .toList();
    }
    image = json['image']?.toString();
    color = json['color']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['nameEN'] = nameEN;
    data['descriptionEN'] = descriptionEN;
    data['icon'] = icon;
    data['iconType'] = iconType;
    data['iconSize'] = iconSize;
    data['className'] = className;
    data['isActive'] = isActive;
    data['code'] = code;
    data['allowEdit'] = allowEdit;
    data['categoryTypeId'] = categoryTypeId;
    data['sortOrder'] = sortOrder;
    data['isDefault'] = isDefault;
    data['createBy'] = createBy;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['parentId'] = parentId;
    data['parent'] = parent?.toJson();
    data['children'] = children?.map((e) => e.toJson()).toList();
    data['image'] = image;
    data['color'] = color;
    return data;
  }
}
