// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8EPrTx9N5DPGh4F9iJ7IclvIHMmb1Lso',
    appId: '1:534175741610:android:b873b13c6a5d001b3c42d3',
    messagingSenderId: '534175741610',
    projectId: 'readbox-3c692',
    storageBucket: 'readbox-3c692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsMWsErHIiOnE57WTyaUBsGpN2n03rR8c',
    appId: '1:534175741610:ios:1624db9508c9f88e3c42d3',
    messagingSenderId: '534175741610',
    projectId: 'readbox-3c692',
    storageBucket: 'readbox-3c692.firebasestorage.app',
    iosClientId: '534175741610-44bsn5bprdk2aahkl86k8ln36ckqe62g.apps.googleusercontent.com',
    iosBundleId: 'com.hungvv.readbox',
  );
}
